work_dir: ./work_dir/ntu/xview/aagcn_joint_aagcn_3gcn_useA_3tcn_w_5913
model_saved_name: ./runs/ntu_cs_aagcn_joint
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/ntu/xview/train_data_joint.npy
  label_path: ./data/ntu/xview/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ./data/ntu/xview/val_data_joint.npy
  label_path: ./data/ntu/xview/val_label.pkl

# model
model: model.aagcn_3gcn_useA_3tcn_w_5913.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial_3'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [30, 40]
warm_up_epoch: 5

# training
device: [0]
batch_size: 16
test_batch_size: 16
num_epoch: 50
nesterov: True

only_train_part: True
only_train_epoch: 5